version: 2
updates:
  - package-ecosystem: "npm"
    directory: '/client' # Location of package.json
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix'
    open-pull-requests-limit: 0 # Increase the limit as needed

  - package-ecosystem: "npm"
    directory: '/app' # Location of package.json
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix'
    open-pull-requests-limit: 0 # Increase the limit as needed